dist: trusty
sudo: true

language: node_js
node_js:
  - "7"
  - "8"
  - "9"

cache:
  directories:
    - "node_modules"

before_install:
  - sudo apt-get install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++

before_script:
  - npm install

script:
  - npm test

notifications:
  email:
    on_success: never
    on_failure: never