dist: trusty
sudo: true

language: node_js
node_js:
  - "7"
  - "8"
  - "9"

cache:
  directories:
    - "node_modules"

before_script:
  - npm install

script:
  - npm test

notifications:
  email:
    on_success: never
    on_failure: never